<template>
  <div class="planet">
    <div id="images">
      <img src="../../assets/img/planets/pluto.jpg" alt="Pluto" class="planet_images img-fluid">
      <img src="../../assets/img/planets/pluto2.jpg" alt="Pluto" class="planet_images img-fluid">
      <img src="../../assets/img/planets/pluto_inside.jpg" alt="Pluto" class="planet_images img-fluid">
      <img src="../../assets/img/planets/pluto_size.jpg" alt="Pluto" class="planet_images img-fluid" style="height:250px;">
    </div>
    <div class="planet_info">
      <h5 class="planet_name">PLUTO</h5>
      <h6 class="planet_info">Pluto (minor planet designation: 134340 Pluto) is a dwarf planet in the Kuiper belt, a ring of bodies beyond Neptune. It was the first Kuiper belt object to be discovered.
      Pluto was discovered by Clyde Tombaugh in 1930 and was originally considered to be the ninth planet from the Sun. After 1992, its status as a planet was questioned following the discovery of several objects of similar size in the Kuiper belt. In 2005, Eris, a dwarf planet in the scattered disc which is 27% more massive than Pluto, was discovered. This led the International Astronomical Union (IAU) to define the term "planet" formally in 2006, during their 26th General Assembly.<br>
      That definition excluded Pluto and reclassified it as a dwarf planet.
      Pluto is the largest and second-most-massive known dwarf planet in the Solar System, and the ninth-largest and tenth-most-massive known object directly orbiting the Sun. It is the largest known trans-Neptunian object by volume but is less massive than Eris. Like other Kuiper belt objects, Pluto is primarily made of ice and rock and is relatively small—about one-sixth the mass of the Moon and one-third its volume. It has a moderately eccentric and inclined orbit during which it ranges from 30 to 49 astronomical units or AU (4.4–7.4 billion km) from the Sun. This means that Pluto periodically comes closer to the Sun than Neptune, but a stable orbital resonance with Neptune prevents them from colliding. Light from the Sun takes about 5.5 hours to reach Pluto at its average distance (39.5 AU).
      Pluto has five known moons: Charon (the largest, with a diameter just over half that of Pluto), Styx, Nix, Kerberos, and Hydra. Pluto and Charon are sometimes considered a binary system because the barycenter of their orbits does not lie within either body.
      On July 14, 2015, the New Horizons spacecraft became the first spacecraft to fly by Pluto. During its brief flyby, New Horizons made detailed measurements and observations of Pluto and its moons.<br>In September 2016, astronomers announced that the reddish-brown cap of the north pole of Charon is composed of tholins, organic macromolecules that may be ingredients for the emergence of life, and produced from methane, nitrogen and other gases released from the atmosphere of Pluto and transferred about 19,000 km (12,000 mi) to the orbiting moon.<br><br>
      <span class="highlight_text">Orbit</span><br>
      Pluto's orbital period is currently about 248 years. Its orbital characteristics are substantially different from those of the planets, which follow nearly circular orbits around the Sun close to a flat reference plane called the ecliptic.<br>In contrast, Pluto's orbit is moderately inclined relative to the ecliptic (over 17°) and moderately eccentric (elliptical). This eccentricity means a small region of Pluto's orbit lies closer to the Sun than Neptune's. The Pluto–Charon barycenter came to perihelion on September 5, 1989,[2][h] and was last closer to the Sun than Neptune between February 7, 1979, and February 11, 1999.[72]
      In the long term, Pluto's orbit is chaotic. Computer simulations can be used to predict its position for several million years (both forward and backward in time), but after intervals longer than the Lyapunov time of 10–20 million years, calculations become speculative: Pluto is sensitive to immeasurably small details of the Solar System, hard-to-predict factors that will gradually change Pluto's position in its orbit.[73][74]
      The semi-major axis of Pluto's orbit varies between about 39.3 and 39.6 au with a period of about 19,951 years, corresponding to an orbital period varying between 246 and 249 years. The semi-major axis and period are presently getting longer.<br><br>
      <span class="highlight_text">Relationship with Neptune</span><br>
      Despite Pluto's orbit appearing to cross that of Neptune when viewed from directly above, the two objects' orbits are aligned so that they can never collide or even approach closely.
      The two orbits do not intersect.<br>When Pluto is closest to the Sun, and hence closest to Neptune's orbit as viewed from above, it is also the farthest above Neptune's path. Pluto's orbit passes about 8 AU above that of Neptune, preventing a collision.
      This alone is not enough to protect Pluto; perturbations from the planets (especially Neptune) could alter Pluto's orbit (such as its orbital precession) over millions of years so that a collision could be possible. However, Pluto is also protected by its 2:3 orbital resonance with Neptune: for every two orbits that Pluto makes around the Sun, Neptune makes three. Each cycle lasts about 495 years. This pattern is such that, in each 495-year cycle, the first time Pluto is near perihelion, Neptune is over 50° behind Pluto. By Pluto's second perihelion, Neptune will have completed a further one and a half of its own orbits, and so will be nearly 130° ahead of Pluto. Pluto and Neptune's minimum separation is over 17 AU, which is greater than Pluto's minimum separation from Uranus (11 AU).The minimum separation between Pluto and Neptune actually occurs near the time of Pluto's aphelion.
      The 2:3 resonance between the two bodies is highly stable, and has been preserved over millions of years.This prevents their orbits from changing relative to one another, and so the two bodies can never pass near each other. Even if Pluto's orbit were not inclined, the two bodies could never collide.<br>The long term stability of the mean-motion resonance is due to phase protection.<br>If Pluto's period is slightly shorter than 3/2 of Neptune its orbit relative to Neptune will drift, causing it to make closer approaches behind Neptune's orbit. The strong gravitational pull between the two causes angular momentum to be transferred to Pluto, at Neptune's expense. This moves Pluto into a slightly larger orbit, where it travels slightly more slowly, according to Kepler's third law. After many such repetitions, Pluto is sufficiently slowed, and Neptune sufficiently sped up, that Pluto orbit relative to Neptune drifts in the opposite direction until the process is reversed. The whole process takes about 20,000 years to complete.<br><br>
      <span class="highlight_text">Rotation</span><br>
      Pluto's rotation period, its day, is equal to 6.39 Earth days.Like Uranus, Pluto rotates on its "side" in its orbital plane, with an axial tilt of 120°, and so its seasonal variation is extreme; at its solstices, one-fourth of its surface is in continuous daylight, whereas another fourth is in continuous darkness.
      The reason for this unusual orientation has been debated.<br>Research from the University of Arizona has suggested that it may be due to the way that a body's spin will always adjust to minimise energy. This could mean a body reorienting itself to put extraneous mass near the equator and regions lacking mass tend towards the poles. This is called polar wander. According to a paper released from the University of Arizona, this could be caused by masses of frozen nitrogen building up in shadowed areas of the dwarf planet. These masses would cause the body to reorient itself, leading to its unusual axial tilt of 120°. The buildup of nitrogen is due to Pluto's vast distance from the Sun. At the equator, temperatures can drop to −240 °C (−400.0 °F; 33.1 K), causing nitrogen to freeze as water would freeze on Earth. The same effect seen on Pluto would be observed on Earth if the Antarctic ice sheet was several times larger<br><br>
      <span class="highlight_text">Surrface</span><br>
      The plains on Pluto's surface are composed of more than 98 percent nitrogen ice, with traces of methane and carbon monoxide.Nitrogen and carbon monoxide are most abundant on the anti-Charon face of Pluto (around 180° longitude, where Tombaugh Regio's western lobe, Sputnik Planitia, is located), whereas methane is most abundant near 300° east.<br>The mountains are made of water ice.Pluto's surface is quite varied, with large differences in both brightness and color.Pluto is one of the most contrastive bodies in the Solar System, with as much contrast as Saturn's moon Iapetus.The color varies from charcoal black, to dark orange and white.[93] Pluto's color is more similar to that of Io with slightly more orange and significantly less red than Mars.[94] Notable geographical features include Tombaugh Regio, or the "Heart" (a large bright area on the side opposite Charon), Cthulhu Macula, or the "Whale" (a large dark area on the trailing hemisphere), and the "Brass Knuckles" (a series of equatorial dark areas on the leading hemisphere).
      Sputnik Planitia, the western lobe of the "Heart", is a 1,000 km-wide basin of frozen nitrogen and carbon monoxide ices, divided into polygonal cells, which are interpreted as convection cells that carry floating blocks of water ice crust and sublimation pits towards their margins there are obvious signs of glacial flows both into and out of the basin.It has no craters that were visible to New Horizons, indicating that its surface is less than 10 million years old.Latest studies have shown that the surface has an age of 180000+90000
      −40000 years.<br>The New Horizons science team summarized initial findings as "Pluto displays a surprisingly wide variety of geological landforms, including those resulting from glaciological and surface–atmosphere interactions as well as impact, tectonic, possible cryovolcanic, and mass-wasting processes.<br><br>
      <span class="highlight_text">Internal structure</span><br>
      1. Frozen nitrogen
      2. Water ice
      3. Rock<br>
      Pluto's density is 1.860±0.013 g/cm3.Because the decay of radioactive elements would eventually heat the ices enough for the rock to separate from them, scientists expect that Pluto's internal structure is differentiated, with the rocky material having settled into a dense core surrounded by a mantle of water ice. The diameter of the core is hypothesized to be approximately 1700 km, 70% of Pluto's diameter.It is possible that such heating continues today, creating a subsurface ocean of liquid water 100 to 180 km thick at the core–mantle boundary.In September 2016, scientists at Brown University simulated the impact thought to have formed Sputnik Planitia, and showed that it might have been the result of liquid water upwelling from below after the collision, implying the existence of a subsurface ocean at least 100 km deep.[106] Pluto has no magnetic field.<br><br>
      Pluto's diameter is 2376.6±3.2 km and its mass is (1.303±0.003)×1022 kg, 17.7% that of the Moon (0.22% that of Earth).Its surface area is 1.779×107 km2, or roughly the same surface area as Russia. Its surface gravity is 0.063 g (compared to 1 g for Earth).
      The discovery of Pluto's satellite Charon in 1978 enabled a determination of the mass of the Pluto–Charon system by application of Newton's formulation of Kepler's third law. Observations of Pluto in occultation with Charon allowed scientists to establish Pluto's diameter more accurately, whereas the invention of adaptive optics allowed them to determine its shape more accurately.<br>
      Size comparisons (to the right): Earth, the Moon, and Pluto
      With less than 0.2 lunar masses, Pluto is much less massive than the terrestrial planets, and also less massive than seven moons: Ganymede, Titan, Callisto, Io, the Moon, Europa, and Triton. The mass is much less than thought before Charon was discovered.
      Pluto is more than twice the diameter and a dozen times the mass of the dwarf planet Ceres, the largest object in the asteroid belt. It is less massive than the dwarf planet Eris, a trans-Neptunian object discovered in 2005, though Pluto has a larger diameter of 2376.6 km compared to Eris's approximate diameter of 2326 km
      </h6>
    </div>
  </div>
</template>


<style scoped>
</style>
